version: 2
updates:
  - package-ecosystem: npm
    directory: "/uol-backend-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 99

  - package-ecosystem: npm
    directory: "/uol-backend-service"
    schedule:
      interval: daily
    open-pull-requests-limit: 99
    
  - package-ecosystem: github-actions
    directory: "/.github"
    schedule:
      interval: daily
    open-pull-requests-limit: 99