
name: 4. Deploy Node Backend API

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push: 
    branches: 
      - main
    paths:
      - 'backend_nodejs_app/**'

jobs:
  nodejsBackendService:
    name: Deploy NodeJS Backend API
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: uollumen.southeastasia.cloudapp.azure.com
          username: uol_admin
          key: ${{secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            sudo kill $(sudo lsof -t -i:5000)
            cd ~/uol
            git remote add uol_invoice_repo https://${{ secrets.GIT_TOKEN }}@github.com/kaleeswaran393/uol.git           
            git pull
            cd backend_nodejs_app
            sudo npm install
            nohup sudo forever start index.js &