
name: Deploy Node App

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push: 
    branches: 
      - main
    paths:
      - 'uol_backend_service/**'
jobs:
  build:
    name: Deploy Node App
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: 20.43.168.65
          username: uol_admin
          key: ${{secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            sudo chown -R uol_admin:root /home/uol_admin/*
            sudo chown -R uol_admin:root /home/uol_admin
            rm -R -f uol
            git clone https://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@github.com/kaleeswaran393/uol.git
            cd uol/uol_backend_service
            sudo forever start index.js
