
name: Deploy Node App

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push: 
    branches: 
      - main
    paths:
      - 'uol_backend_service/**'

jobs:
  build:
    name: Deploy Node App
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VM_IP_ADDRESS }}
          username: uol_admin
          key: ${{secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            sudo chown -R uol_admin:root /home/uol_admin/
            sudo chown -R uol_admin:root /home/uol_admin/
            rm -R -f uol
            git clone https://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@github.com/kaleeswaran393/uol.git
            sudo apt install nodejs npm -y
            sudo npm install forever -g
            sudo npm i express -y
            sudo npm i mysql2 -y
            cd uol/uol_backend_service
            sudo forever start index.js