name: Build Typescript

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push: 
    branches: 
      - main
    paths:
      - 'uol_backend_service/**'

jobs:
  build:
    name: Build Typescript
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Using Node ${{ matrix.node-version }}
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Set SSH Key
        run: |
          ls '${{ env.OUTPUT_PATH }}'
          '${{secrets.UOL_SSH_KEY }}' > ${{ env.OUTPUT_PATH }}/sec.pub

      - name: Cache NPM packages
        uses: actions/cache@v2.1.4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - name: Build
        working-directory: ./uol_backend_service # Make sure we run our UI commands in the UI directory
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          npm i express
          npm i mysql2
      - uses: actions/checkout@v2
      - name: ssh deploy
        uses: easingthemes/ssh-deploy@v2.1.4
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          REMOTE_HOST: 20.43.168.65
          REMOTE_USER: uol_admin
          REMOTE_PORT: 22
          SOURCE: "${{ github.workspace }}/uol_backend_service"
          TARGET: /home/uol_admin/uol_backend_service