
on: 
  push: 
    branches: 
      - main
    paths:
      - 'infrastructure_arm/**'

name: Azure ARM Template To Create VM
env:
  OUTPUT_PATH: ${{ github.workspace }}
jobs:
  createVMUsingARM:
    runs-on: ubuntu-latest
    steps:
    - name: Install Azure cli
      run: |
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-cli
    - name: look for ps1 file
      run: |
        az --help
      # Checkout code
      # az role assignment create --assignee cd5fad2d-8d17-493d-81f8-d7583cd55eae --role Owner   --subscription ba5cad7f-06ec-4765-aec0-c3caed478b73
      # az ad sp create-for-rbac --name uol --role contributor --scopes /subscriptions/ba5cad7f-06ec-4765-aec0-c3caed478b73/resourceGroups/uol_vm_resource_group --sdk-auth
    - uses: actions/checkout@main

      # Log into Azure
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy ARM template
    - name: Run ARM deploy
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: uol_vm_resource_group
        template: ${{ env.OUTPUT_PATH }}/infrastructure_arm/uol_invoice_vm.json
        scope: resourcegroup
        #parameters: storageAccountType=Standard_LRS

      # output containerName variable from template
    - run: echo ${{ steps.deploy.outputs.containerName }}