name: GitHub for IT Pro CI/CD Pipeline

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push:
    branches: 
      - main
    paths:
      - 'infrastructure_az_cli/**'

jobs:
      
  # Deploy VM in Azure
  DeployVM:
    runs-on: windows-latest

    steps:
    
    - name: remove virtual machine in azure
      env:
        RESOURCE_GROUP: uol_vm_resource_group
        RESOURCE_GROUP_REGION: southeastasia
      run: >
        powershell -command "& '${{ env.OUTPUT_PATH }}\infrastrcuture_az_cli\create_vm.ps1'"
        -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} 
        -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }} 
        -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        -resourceGroupName %RESOURCE_GROUP% 
        -resourceGroupNameRegion %RESOURCE_GROUP_REGION% 


