
name: 2. Install Sofware and Packages

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push: 
    branches: 
      - main
    paths:
      - 'package_installation_script/**'

jobs:
  installSofwareAndPackages:
    name: VM setup
    runs-on: ubuntu-latest
    steps:
      - name: Install Software And Packages Using SSH
        uses: appleboy/ssh-action@master
        with:
          host: uollumen.southeastasia.cloudapp.azure.com
          username: uol_admin
          key: ${{secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            sudo chown -R uol_admin:root /home/uol_admin/
            sudo chown -R uol_admin:root /home/uol_admin/
            rm -R -f uol
            git clone https://${{ secrets.GIT_TOKEN }}@github.com/kaleeswaran393/uol.git
            sudo apt update
            sudo apt install nodejs npm -y
            sudo npm install forever -g
            sudo npm i express -y
            sudo npm i mysql2 -y
            sudo apt update
            sudo apt install nginx -y
            sudo ufw allow 'Nginx HTTP'
            sudo mkdir  /etc/nginx/ssl
            sudo openssl req -x509 -nodes -days 365 -newkey rsa:2048 -subj "/C=SG/ST=Singapore/L=Singapore/O=Global Security/OU=IT Department/CN=uollumen.com" -keyout /etc/nginx/ssl/nginx.key -out /etc/nginx/ssl/nginx.crt
            sudo cp /home/uol_admin/uol/install_package/default /etc/nginx/sites-available
            sudo service nginx restart
            sudo apt install wget ca-certificates
            wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
            sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ $(lsb_release -cs)-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
            sudo apt update
            sudo apt install postgresql postgresql-contrib -y
            sudo service postgresql status
