
name: Intial VM setup

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push: 
    branches: 
      - main
    paths:
      - 'uol_ui/**'

jobs:
  deployNodeExperessJss:
    name: Deploy expressJs App
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.VM_IP_ADDRESS }}
          username: uol_admin
          key: ${{secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ~
            sudo chown -R uol_admin:root /home/uol_admin/
            rm -R -f uol
            git clone https://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@github.com/kaleeswaran393/uol.git
            sudo npm install -g @angular/cli -y
            sudo npm install @azure/msal-browser @azure/msal-angular -y
            sudo npm install @angular/material @angular/cdk -y
            sudo npm run start&
        
