name: 1.Provision VM on Azure

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push:
    branches: 
      - main
    paths:
      - 'vm_creation_script/**'
jobs:
      
  createAzureVirtualMachine:
    runs-on: windows-latest
    steps:

    - name: checkout repo
      uses: actions/checkout@v1

    - name: Store public key in a file
      run: |
        ls '${{ env.OUTPUT_PATH }}'
        '${{secrets.UOL_SSH_KEY }}' > ${{ env.OUTPUT_PATH }}/sec.pub
        ls ${{ env.OUTPUT_PATH }}
        
    - name: Provision VM on Azure
      env:
        RESOURCE_GROUP: uol_vm_resource_group
        RESOURCE_GROUP_REGION: southeastasia
        SERVER_NAME: uol_invoice_app_server
        ADMIN_LOGIN: uol_admin
      run: >
        powershell -command "& '${{ env.OUTPUT_PATH }}\vm_creation_script\vm_provisioning.ps1'"
        -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} 
        -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }} 
        -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        -resourceGroupName %RESOURCE_GROUP% 
        -resourceGroupNameRegion %RESOURCE_GROUP_REGION% 
        -serverName %SERVER_NAME% 
        -adminLogin %ADMIN_LOGIN% 
        -adminPassword ${{ secrets.VM_ADMIN_PASSWORD }} 
        -uolsshkey ${{ env.OUTPUT_PATH }}\sec.pub
        -current_path ${{ env.OUTPUT_PATH }}
        -ipAddress ${{secrets.VM_IP_ADDRESS }}



