name: 5.Delete Azure VM

env:
  OUTPUT_PATH: ${{ github.workspace }}

on: 
  push:
    branches: 
      - main
    paths:
      - 'vm_cleanup_script/**'
jobs:
      
  deleteAzureVirtualMachine:
    runs-on: windows-latest
    steps:
    - name: checkout repo
      uses: actions/checkout@v1
      
    - name: Delete Azure VM
      env:
        RESOURCE_GROUP: uol_vm_resource_group
        RESOURCE_GROUP_REGION: southeastasia
      run: >
        powershell -command "& '${{ env.OUTPUT_PATH }}\vm_cleanup_script\delete_vm_resource.ps1'"
        -servicePrincipal ${{ secrets.SERVICE_PRINCIPAL_APPID }}
        -servicePrincipalSecret ${{ secrets.SERVICE_PRINCIPAL_SECRET }} 
        -servicePrincipalTenantId ${{ secrets.SERVICE_PRINCIPAL_TENANTID }} 
        -azureSubscriptionName ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        -resourceGroupName %RESOURCE_GROUP% 
        -resourceGroupNameRegion %RESOURCE_GROUP_REGION% 


